export const defaultEvents = [
  {
    slug: "ship-something-weird",
    number: "001",
    title: "Ship Something Weird",
    eyebrow: "the next paper boat",
    status: "open",
    eventMode: "online",
    startDate: "",
    date: "Date dropping soon · 8 PM start",
    dateShort: "24 hrs",
    timezone: "Asia/Singapore · GMT+8",
    location: "Online · worldwide",
    venue: "Online build room · link sent to registered builders",
    meetingUrl: "",
    capacity: 0,
    spotsLeft: null,
    description:
      "From 8 PM to 8 PM the next day: build a software product with AI, ship it, and get real people to use it before the 24-hour clock runs out.",
    longDescription:
      "Paper Boat is an online-first 24-hour AI build-and-growth challenge for developers, designers, students and serial side-project starters. The build clock starts at 8 PM and stops at 8 PM the next day. Use AI tools, agents, APIs, open models, no-code or anything else that helps you move fast. Ship a working software product and pull in as many real users as you can during those same 24 hours. From 8 PM to 9 PM after the build window, everyone demos what they shipped and results are judged.",
    topic: "Build a useful software product and get real users in 24 hours.",
    recap: "",
    judging: [
      "Functionality — does the product work, and how complete/useful is it?",
      "Traction — how many real users did you acquire inside the 24-hour window?",
    ],
    prompts: [
      "make a tool your 12-year-old self would use",
      "replace one boring workflow with an agent",
      "build a terrible idea extremely well",
      "make the internet feel human again",
    ],
    schedule: [
      { time: "19:30", label: "online room opens + introductions" },
      { time: "20:00", label: "24-hour clock starts — build begins" },
      { time: "00:00", label: "midnight checkpoint + user-acquisition plans" },
      { time: "08:00 +1", label: "halfway checkpoint — keep building + keep growing" },
      { time: "16:00 +1", label: "final four-hour push" },
      { time: "20:00 +1", label: "ship. build + growth window closes." },
      { time: "20:00–21:00 +1", label: "live demos + judging + results" },
    ],
    onlineGuide: [
      "Deploy something usable in the first few hours — do not wait for polish.",
      "Start sharing early. Your first users should influence what you build next.",
      "Keep one visible traction metric: sign-ups, active users, sessions or another honest usage signal.",
      "Freeze risky features in the final four hours and focus on reliability plus distribution.",
      "Keep proof of traction ready for judging: analytics, sign-ups, active users or usage screenshots.",
      "For the 8–9 PM demo hour: show the product first, then the user numbers, then what you learned.",
    ],
    offlineFlow: [],
    showcase: [],
    tags: ["AI", "agents", "software", "growth", "online", "ship in 24h", "real users"],
  },
  {
    slug: "hello-world",
    number: "000",
    title: "Hello, World",
    eyebrow: "the paper boat pilot",
    status: "past",
    eventMode: "online",
    startDate: "",
    date: "Pilot edition",
    dateShort: "shipped",
    timezone: "Asia/Singapore · GMT+8",
    location: "Online",
    venue: "Pilot online build room",
    meetingUrl: "",
    capacity: 0,
    spotsLeft: 0,
    description:
      "The messy little pilot where the rule was simple: build, ship, and get it in front of someone.",
    longDescription:
      "A tiny first run to test the format: a 24-hour online build, a working launch, and a demo circle at the end.",
    topic: "A pilot edition to test whether builders could go from idea to shipped product in one day.",
    recap:
      "This was the format test for Paper Boat: a small online room, a strict 24-hour clock, lightweight checkpoints and a final demo circle. The public participant and project archive can be filled from the organizer console once those details are ready to publish.",
    judging: ["Functionality", "Real users reached during the challenge"],
    prompts: [
      "talk to a PDF",
      "make a tiny multiplayer toy",
      "build with one API you've never used",
    ],
    schedule: [
      { time: "20:00", label: "build starts" },
      { time: "20:00 +1", label: "ship" },
      { time: "20:00–21:00 +1", label: "demos + results" },
    ],
    onlineGuide: [],
    offlineFlow: [],
    showcase: [],
    tags: ["pilot", "AI", "online build"],
  },
];
